#!/bin/bash
#
# Unix bash shell script to apply post-processing patches to the generated source
# code. This should be run only after source code has been newly generated by the
# XMPP utility. This should be done automatically on Unix-derived operating systems
# via the ant task. You're on your own for windows.
#
# Since this is run from the project directory (one level above this), all the
# file names used should be relative to that directory.
#
# Uses the Unix patch utility.
#
# To generate a patch file, check out the current source code from svn, then
# modify it. Run the command
# svn diff SomeFile.java > SomeFile.java.patch
# to create the patch file
#
# @author DMcG
# @version $Id:$

# Pdu.java, apply patch file
patch java/edu/nps/moves/dis/Pdu.java patches/java/Pdu.java.patch

# Marking.java, apply patch file
patch java/edu/nps/moves/dis/Marking.java patches/java/Marking.java.patch

# EntityStatePdu.java, apply patch file
patch java/edu/nps/moves/dis/EntityStatePdu.java patches/java/EntityStatePdu.java.patch

# ArticulationParameter.java, apply patch file
patch java/edu/nps/moves/dis/ArticulationParameter.java patches/java/ArticulationParameter.java.patch

# DeadReckoningParameter.java, apply patch file
patch java/edu/nps/moves/dis/DeadReckoningParameter.java patches/java/DeadReckoningParameter.java.patch

# Orientation.java, apply patch file
patch java/edu/nps/moves/dis/Orientation.java patches/java/Orientation.java.patch

# Vector3Float.java, apply patch file
patch java/edu/nps/moves/dis/Vector3Float.java patches/java/Vector3Float.java.patch

# Apply patch to VariableDatum.java
patch java/edu/nps/moves/dis/VariableDatum.java patches/java/VariableDatum.java.patch

# Apply patches to c++ code....

